plugins {
    id 'java'
    id "io.qameta.allure" version "2.12.0"
}

repositories {
    mavenCentral()
}

dependencies {
    // Selenium
    implementation 'org.seleniumhq.selenium:selenium-java:4.21.0'

    // TestNG
    testImplementation 'org.testng:testng:7.10.2'

    // Allure TestNG
    testImplementation 'io.qameta.allure:allure-testng:2.24.0'
}

test {
    useTestNG()

    testLogging {
        events "passed", "skipped", "failed"
    }
}

/* Run ONLY LocatorsTest */
tasks.register('runLocatorsTest', Test) {
    useTestNG()
    include '**/LocatorsTest.class'
}

/* Date format for report */
import java.text.SimpleDateFormat
def currentDate = new SimpleDateFormat("yyyy-MM-dd_HH-mm").format(new Date())

/* Allure report for LocatorsTest ONLY */
tasks.register("locatorsReport", Exec) {
    dependsOn runLocatorsTest
    commandLine "cmd", "/c",
            "allure generate build/allure-results -o build/locators-report-${currentDate} --clean"
}

allure {
    version = "2.24.0"
    autoconfigure = true
    aspectjweaver = true
}